version: "3.9"
services:
  # redis:
  #   image: redis
  #   container_name: redis
  #   env_file: .env
  #   ports: 
  #    - "${REDIS_PORT}:${REDIS_PORT}"
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  postgres:
    image: postgres
    container_name: postgres
    env_file: .env
    ports: 
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: "Europe/Moscow"
